import { config, library } from "@fortawesome/fontawesome-svg-core";
import {
  faCalendarDays,
  faChevronRight,
  faCircleCheck,
  faClock,
  faCompass,
  faHeart,
  faHouseChimney,
  faList,
  faLocationArrow,
  faMagnifyingGlass,
  faMapLocationDot,
  faMobileScreen,
  faPersonHiking,
  faRoute,
  faShoppingCart,
  faStar,
  faStore,
  faTicket,
  faUser,
  faUserGroup,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
  faCalendarDays,
  faChevronRight,
  faCircleCheck,
  faClock,
  faCompass,
  faHeart,
  faHouseChimney,
  faList,
  faLocationArrow,
  faMagnifyingGlass,
  faMapLocationDot,
  faMobileScreen,
  faPersonHiking,
  faRoute,
  faShoppingCart,
  faStar,
  faStore,
  faTicket,
  faUser,
  faUserGroup,
  faUsers,
  faXmark,
);

export {
  faCalendarDays,
  faChevronRight,
  faCircleCheck,
  faClock,
  faCompass,
  faHeart,
  faHouseChimney,
  faList,
  faLocationArrow,
  faMagnifyingGlass,
  faMapLocationDot,
  faMobileScreen,
  faPersonHiking,
  faRoute,
  faShoppingCart,
  faStar,
  faStore,
  faTicket,
  faUser,
  faUserGroup,
  faUsers,
  faXmark,
};
