export const FALLBACK_STAYS = [
  {
    id: "stay-1",
    slug: "sowon-house-01",
    title: "소원 낙조 펜션",
    summary: "만리포 해변이 한눈에 보이는 바다 전망 펜션",
    description: "서해의 아름다운 낙조를 거실에서 감상할 수 있는 고품격 펜션입니다. 가족 단위 여행객에게 최적화된 넓은 공간과 편의시설을 갖추고 있습니다.",
    address: "충남 태안군 소원면 만리포해수욕장길 123",
    priceText: "평일 120,000원 ~",
    capacityText: "기준 2인 / 최대 4인",
    images: ["/images/stays/stay-01.jpg"],
    phone: "010-0000-0001",
    kakaoUrl: "https://pf.kakao.com/_xxxx",
    naverBookingUrl: "https://booking.naver.com/booking/3/bizes/123",
    websiteUrl: "https://example.com",
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-2",
    slug: "cheonripo-minbak",
    title: "천리포 파랑새 민박",
    summary: "어촌 마을의 정취를 느낄 수 있는 소박한 민박",
    description: "천리포 해변 인근의 조용한 마을에 위치한 민박입니다. 할머니의 손맛이 담긴 아침 식사와 따뜻한 온돌방이 준비되어 있습니다.",
    address: "충남 태안군 소원면 천리포길 45",
    priceText: "50,000원",
    capacityText: "기준 1인 / 최대 2인",
    images: ["/images/stays/stay-02.jpg"],
    phone: "010-0000-0002",
    kakaoUrl: null,
    naverBookingUrl: null,
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-3",
    slug: "uihang-hanok-stay",
    title: "의항 한옥 스테이",
    summary: "소나무 숲과 바다 산책로가 가까운 조용한 한옥 숙소",
    description: "의항 해변과 솔숲 산책로를 함께 즐길 수 있는 한옥형 숙소입니다. 작은 마당과 온돌방을 갖춰 가족 여행이나 조용한 휴식에 어울립니다.",
    address: "충남 태안군 소원면 의항리길 78",
    priceText: "평일 90,000원 ~",
    capacityText: "기준 2인 / 최대 4인",
    images: ["/images/courses/course-02.jpg"],
    phone: "010-0000-0003",
    kakaoUrl: "https://pf.kakao.com/_example3",
    naverBookingUrl: null,
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-4",
    slug: "mallipo-glamping",
    title: "만리포 바다 글램핑",
    summary: "해변 가까이에서 캠핑 분위기를 즐기는 감성 글램핑",
    description: "만리포 해변 접근성이 좋은 글램핑형 숙소입니다. 바다 산책과 노을 감상을 중심으로 짧은 체류 여행을 계획하기 좋습니다.",
    address: "충남 태안군 소원면 만리포2길 31",
    priceText: "평일 110,000원 ~",
    capacityText: "기준 2인 / 최대 3인",
    images: ["/images/stays/stay-04.jpg"],
    phone: "010-0000-0004",
    kakaoUrl: null,
    naverBookingUrl: "https://booking.naver.com/example4",
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  }
];
