import { ExperienceUI } from "../src/lib/experience-data";
import { LocalIncomeProgramUI } from "../src/lib/program-data";
import { CourseUI } from "../src/lib/course-data";
import { PublishStatus, CourseItemType } from "@prisma/client";

export const FALLBACK_STAYS = [
  {
    id: "stay-1",
    slug: "sowon-house-01",
    title: "소원 낙조 펜션",
    summary: "만리포 해변이 한눈에 보이는 바다 전망 펜션",
    description: "서해의 아름다운 낙조를 거실에서 감상할 수 있는 고품격 펜션입니다. 가족 단위 여행객에게 최적화된 넓은 공간과 편의시설을 갖추고 있습니다.",
    address: "충남 태안군 소원면 만리포해수욕장길 123",
    priceText: "평일 120,000원 ~",
    capacityText: "기준 2인 / 최대 4인",
    images: ["/images/stays/stay-01.jpg"],
    phone: "010-0000-0001",
    kakaoUrl: "https://pf.kakao.com/_xxxx",
    naverBookingUrl: "https://booking.naver.com/booking/3/bizes/123",
    websiteUrl: "https://example.com",
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-2",
    slug: "cheonripo-minbak",
    title: "천리포 파랑새 민박",
    summary: "어촌 마을의 정취를 느낄 수 있는 소박한 민박",
    description: "천리포 해변 인근의 조용한 마을에 위치한 민박입니다. 할머니의 손맛이 담긴 아침 식사와 따뜻한 온돌방이 준비되어 있습니다.",
    address: "충남 태안군 소원면 천리포길 45",
    priceText: "50,000원",
    capacityText: "기준 1인 / 최대 2인",
    images: ["/images/stays/stay-02.jpg"],
    phone: "010-0000-0002",
    kakaoUrl: null,
    naverBookingUrl: null,
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-3",
    slug: "uihang-hanok-stay",
    title: "의항 한옥 스테이",
    summary: "소나무 숲과 바다 산책로가 가까운 조용한 한옥 숙소",
    description: "의항 해변과 솔숲 산책로를 함께 즐길 수 있는 한옥형 숙소입니다. 작은 마당과 온돌방을 갖춰 가족 여행이나 조용한 휴식에 어울립니다.",
    address: "충남 태안군 소원면 의항리길 78",
    priceText: "평일 90,000원 ~",
    capacityText: "기준 2인 / 최대 4인",
    images: ["/images/courses/course-02.jpg"],
    phone: "010-0000-0003",
    kakaoUrl: "https://pf.kakao.com/_example3",
    naverBookingUrl: null,
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  },
  {
    id: "stay-4",
    slug: "mallipo-glamping",
    title: "만리포 바다 글램핑",
    summary: "해변 가까이에서 캠핑 분위기를 즐기는 감성 글램핑",
    description: "만리포 해변 접근성이 좋은 글램핑형 숙소입니다. 바다 산책과 노을 감상을 중심으로 짧은 체류 여행을 계획하기 좋습니다.",
    address: "충남 태안군 소원면 만리포2길 31",
    priceText: "평일 110,000원 ~",
    capacityText: "기준 2인 / 최대 3인",
    images: ["/images/stays/stay-04.jpg"],
    phone: "010-0000-0004",
    kakaoUrl: null,
    naverBookingUrl: "https://booking.naver.com/example4",
    websiteUrl: null,
    status: "published",
    regionId: "sowon",
  }
];

export const FALLBACK_EXPERIENCES: ExperienceUI[] = [
  {
    id: "exp-1",
    slug: "mallipo-sunset-walk",
    title: "만리포 노을길 산책",
    summary: "해 질 녘 만리포 해변을 따라 걷는 낭만적인 산책",
    description: "로컬 가이드와 함께 만리포 해변의 숨겨진 노을 명소를 찾아 떠납니다. 서해의 아름다운 낙조를 배경으로 인생 사진을 남겨보세요.",
    category: "해변",
    location: "만리포 해수욕장",
    durationText: "1시간 30분",
    priceText: "15,000원",
    capacityText: "최대 10인",
    images: ['/images/experiences/exp-01.jpg'],
    phone: "010-0000-0001",
    kakaoUrl: "https://pf.kakao.com/_xxxx",
    naverBookingUrl: "https://booking.naver.com/123",
    websiteUrl: null,
    meetingPoint: "만리포 해수욕장 관광안내소 앞",
    preparation: "편안한 운동화, 개인 생수",
    includes: "가이드비, 기념 사진 촬영",
    excludes: "개인 간식, 음료",
    safetyNotice: "기상 악화 시 취소될 수 있습니다. 노을 시간대에 따라 출발 시간이 변동될 수 있습니다.",
    status: PublishStatus.published,
    regionId: "sowon",
  },
  {
    id: "exp-2",
    slug: "gamtae-mini-class",
    title: "감태 미니 클래스",
    summary: "소원면 특산물 감태를 직접 만져보고 맛보는 체험",
    description: "청정 지역에서 자란 감태의 생산 과정을 배우고, 직접 감태를 활용한 간단한 간식을 만들어봅니다.",
    category: "음식",
    location: "소원면 주민센터 인근",
    durationText: "1시간",
    priceText: "20,000원",
    capacityText: "4인 이상",
    images: ['/images/experiences/exp-02.jpg'],
    phone: "010-0000-0002",
    kakaoUrl: null,
    naverBookingUrl: null,
    websiteUrl: "https://example.com/gamtae",
    meetingPoint: "소원면 맛마을 공방",
    preparation: "앞치마 (선택사항)",
    includes: "재료비, 시식비",
    excludes: null,
    safetyNotice: "식품 알레르기가 있는 경우 미리 말씀해 주세요.",
    status: PublishStatus.published,
    regionId: "sowon",
  },
  {
    id: "exp-3",
    slug: "fishing-village-morning-walk",
    title: "어촌 마을의 아침 산책",
    summary: "활기찬 어촌의 아침을 여는 조용한 산책",
    description: "새벽녘 어시장과 조용한 어촌 마을을 둘러보며 진정한 로컬의 일상을 경험합니다.",
    category: "어촌",
    location: "천리포 어촌마을",
    durationText: "1시간",
    priceText: "무료 (팁 기반)",
    capacityText: "제한 없음",
    images: ['/images/experiences/exp-04.jpg'],
    phone: "010-0000-0003",
    kakaoUrl: "https://pf.kakao.com/_yyyy",
    naverBookingUrl: null,
    websiteUrl: null,
    meetingPoint: "천리포 선착장 입구",
    preparation: "따뜻한 외투",
    includes: "마을 안내",
    excludes: "개인 소비 비용",
    safetyNotice: "선착장 근처에서는 안전에 유의해 주세요.",
    status: PublishStatus.published,
    regionId: "sowon",
  },
  {
    id: "exp-4",
    slug: "beachcombing-workshop",
    title: "비치코밍 업사이클링 워크숍",
    summary: "바다의 유리를 보석으로 바꾸는 친환경 체험",
    description: "해변에서 주운 씨글라스를 활용하여 나만의 액세서리를 만듭니다. 바다 환경도 지키고 특별한 추념품도 가져가세요.",
    category: "ESG",
    location: "소원면 공방",
    durationText: "2시간",
    priceText: "25,000원",
    capacityText: "최대 6인",
    images: ['/images/experiences/exp-03.jpg'],
    phone: "010-0000-0004",
    kakaoUrl: null,
    naverBookingUrl: "https://booking.naver.com/456",
    websiteUrl: null,
    meetingPoint: "에코 소원 공방",
    preparation: null,
    includes: "재료 일체, 포장 패키지",
    excludes: null,
    safetyNotice: "유리 조각을 다룰 때 주의가 필요합니다.",
    status: PublishStatus.published,
    regionId: "sowon",
  }
];

export const FALLBACK_PROGRAMS: LocalIncomeProgramUI[] = [
  {
    id: "prog-1",
    slug: "village-dining",
    title: "주민이 차려주는 제철 어촌 밥상",
    summary: "천리포 부녀회에서 직접 잡은 수산물로 차리는 건강한 한 끼",
    description: "제철 해산물과 마을에서 직접 기른 채소를 활용한 한상차림입니다.",
    linkedLifeService: "지역 노인 급식 지원 사업 연계",
    residentRole: "식재료 채집(어촌계), 조리(부녀회)",
    revenueUse: "마을 공동 기금 30%, 참여 주민 활동비 70%",
    location: "천리포 마을 회관",
    priceText: "15,000원",
    durationText: "1시간 30분",
    capacityText: "최소 2인",
    images: ['/images/programs/prog-01.jpg'],
    phone: "010-0000-0002",
    kakaoUrl: null,
    naverBookingUrl: null,
    websiteUrl: null,
    status: PublishStatus.published,
    regionId: "sowon",
    category: "식생활",
    meetingPoint: "천리포 마을 회관 입구",
    preparation: null,
    includes: "제철 어촌 밥상 1인분",
    excludes: null,
    safetyNotice: "식품 알레르기가 있으신 경우 사전에 문의해 주세요.",
  },
  {
    id: "prog-2",
    slug: "salt-farm-tour",
    title: "전통 방식 염전 체험 및 소금 판매",
    summary: "천일염의 고장에서 경험하는 전통 소금 밀기 체험",
    description: "염전 장인과 함께하는 소금 밀기 체험과 프리미엄 천일염 판매",
    linkedLifeService: "청년 귀어 교육 프로그램 연계",
    residentRole: "염전 장인의 교육 및 시연",
    revenueUse: "시설 유지 관리비 및 마을 장학금 적립",
    location: "소원면 염전 일대",
    priceText: "10,000원",
    durationText: "1시간",
    capacityText: "제한 없음",
    images: ['/images/programs/prog-02.jpg'],
    phone: null,
    kakaoUrl: "https://pf.kakao.com/_example1",
    naverBookingUrl: null,
    websiteUrl: null,
    status: PublishStatus.published,
    regionId: "sowon",
    category: "어촌자원",
  },
  {
    id: "prog-3",
    slug: "woodworking-class",
    title: "주민 목공방 기초 클래스 (DRAFT)",
    summary: "마을 목공소에서 배우는 기초 가구 제작",
    linkedLifeService: "마을 노후 주택 수리 봉사단 연계",
    residentRole: "마을 목수님의 재능 기부",
    revenueUse: "공동 작업장 공구 구입비",
    images: ['/images/programs/prog-03.jpg'],
    status: PublishStatus.draft,
    regionId: "sowon",
    category: "공동공간",
  },
  {
    id: "prog-4",
    slug: "sowon-sea-water-playground",
    title: "소원 바다물길 놀이터",
    summary: "자연이 만든 안전한 바다 놀이터에서 즐기는 생태 학습",
    linkedLifeService: "지역 청소년 생태 교육 연계",
    residentRole: "안전 요원 및 생태 해설사",
    revenueUse: "바다 놀이터 환경 정화 기금",
    location: "어은돌 해수욕장 인근",
    priceText: "무료 (기부제)",
    images: ['/images/programs/prog-04.jpg'],
    phone: "010-0000-0004",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "가족체류",
  },
  {
    id: "prog-5",
    slug: "pension-kids-water-yard",
    title: "펜션 마당 키즈 풀장",
    summary: "펜션 마당에서 아이들이 안전하게 즐기는 물놀이장",
    linkedLifeService: "가족 체류형 관광 인프라 개선",
    residentRole: "펜션 운영주 연합 시설 관리",
    revenueUse: "수질 관리 및 안전 장비 확충",
    location: "소원면 펜션 밀집 구역",
    priceText: "이용 시설에 따라 다름",
    images: ['/images/programs/prog-05.jpg'],
    phone: "010-0000-0005",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "가족체류",
  },
  {
    id: "prog-6",
    slug: "local-table-experience",
    title: "태안 로컬 식재료 팜다이닝",
    summary: "지역 농부들이 재배한 식재료로 만드는 특별한 코스 요리",
    linkedLifeService: "지역 농가 판로 확대 및 소득 증대",
    residentRole: "농산물 공급 및 농장 투어 가이드",
    revenueUse: "참여 농가 소득 보전 및 종자 구입",
    location: "소원면 농장 일대",
    priceText: "50,000원",
    images: ['/images/programs/prog-06.jpg'],
    naverBookingUrl: "https://booking.naver.com/456",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "식생활",
  },
  {
    id: "prog-7",
    slug: "gamtae-packing-class",
    title: "수제 감태 선물세트 포장 클래스",
    summary: "지역 특산물 감태를 예쁘게 포장해 선물하는 체험",
    linkedLifeService: "마을 공동 브랜드 가치 향상",
    residentRole: "마을 어르신들의 포장 노하우 전수",
    revenueUse: "어르신 강사 인건비 및 패키지 개발",
    location: "소원면 마을 회관",
    priceText: "30,000원 (감태 포함)",
    images: ['/images/programs/prog-07.jpg'],
    phone: "010-0000-0007",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "주민일자리",
  },
  {
    id: "prog-8",
    slug: "harbor-morning-tour",
    title: "활기찬 항구 아침 투어",
    summary: "경매가 열리는 항구의 아침을 주민 해설사와 함께 걷기",
    linkedLifeService: "어촌 문화 보존 및 알림",
    residentRole: "전직 어부 출신 마을 해설사",
    revenueUse: "어촌계 복지 기금",
    location: "모항항 일대",
    priceText: "무료",
    durationText: "1시간",
    images: ['/images/programs/prog-08.jpg'],
    phone: "010-0000-0008",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "생활인구",
    safetyNotice: "항구 작업 차량과 미끄러운 바닥에 주의하세요.",
  },
  {
    id: "prog-9",
    slug: "shrimp-grill-experience",
    title: "대하 손질·구이 체험",
    summary: "내가 직접 만든 음식의 깊은 만족감, 신선한 대하 손질부터 구이까지",
    description: "참가자가 직접 신선한 태안 대하를 손질하고 최적의 온도로 굽는 과정까지 참여하는 체험입니다. “내가 직접 만든 음식”이라는 만족감이 대단히 높습니다.",
    linkedLifeService: "지역 수산 농가 유통 지원 사업 연계",
    residentRole: "어촌계 대하 손질법 전수 및 굽기 시연",
    revenueUse: "참여 주민 소득 보전 및 어촌 발전 기금",
    location: "백사장 항구 및 제휴 행사장",
    priceText: "25,000원",
    images: ['/images/programs/shrimp-grill.png'],
    phone: "010-0000-0009",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "식생활",
  },
  {
    id: "prog-10",
    slug: "fishing-village-dining-class",
    title: "어촌식 한상 만들기 클래스",
    summary: "지역 어르신이 들려주는 낭만 가득한 태안 전통 조리법 클래스",
    description: "소원면 어촌계 어르신들과 함께 제철 수산물을 활용해 태안 전통 조리법으로 푸짐한 어촌식 한상을 직접 만들어보고 주민의 스토리텔링을 경험하는 클래스입니다.",
    linkedLifeService: "주민 주도형 노인 일자리 사업 활성화 연계",
    residentRole: "부녀회 어르신 조리법 교육 및 스토리텔링 가이드",
    revenueUse: "마을 노인 복지 기금 및 강사 어르신 인건비",
    location: "소원면 복합 주민 센터",
    priceText: "35,000원",
    images: ['/images/programs/dining-class.png'],
    phone: "010-0000-0010",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "식생활",
  },
  {
    id: "prog-11",
    slug: "shrimp-seafood-bbq",
    title: "대하·해산물 바비큐 파티",
    summary: "노을 지는 바닷가에서 즐기는 가족·단체 인기 만점 공동체형 바비큐",
    description: "서해의 낭만적인 노을을 감상하며 대하와 가리비 등 제철 해산물을 직접 굽고 여행객들과 따스하게 교류하는 공동체형 바비큐 프로그램입니다.",
    linkedLifeService: "마을 야간 레저 인프라 개선 연계",
    residentRole: "청년회 바비큐 인프라 조성 및 안전 가이드",
    revenueUse: "마을 야간 안전 설비 유지 및 청년 활동 자금",
    location: "만리포 노을 해변 야외 바비큐 존",
    priceText: "45,000원",
    images: ['/images/programs/seafood-bbq.png'],
    phone: "010-0000-0011",
    status: PublishStatus.published,
    regionId: "sowon",
    category: "식생활",
  }
];

export const FALLBACK_COURSES: CourseUI[] = [
  {
    id: "course-1",
    slug: "sowon-one-day",
    title: "소원면 바다 감성 일일 코스",
    summary: "바다 전망 숙소부터 서핑, 어촌 밥상까지 알차게 즐기는 하루",
    description: "만리포와 천리포를 오가며 바다의 매력을 온전히 느낄 수 있는 당일치기 코스입니다.",
    images: ["/images/courses/course-01.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "가족/커플",
    durationType: "당일",
    season: "여름/가을",
    linkedStayCount: 1,
    linkedExpCount: 1,
    linkedProgCount: 1,
    routeItems: [
      {
        id: "ci-1-1",
        itemType: CourseItemType.accommodation,
        sortOrder: 1,
        time: "오전 10:00",
        title: "만리포 해변 산책",
        note: "숙소 주변에서 아침 산책",
        slug: "sowon-house-01"
      },
      {
        id: "ci-1-2",
        itemType: CourseItemType.experience,
        sortOrder: 2,
        time: "오후 2:00",
        title: "만리포 서핑 클래스",
        note: "초보자를 위한 입문 강습",
        slug: "mallipo-sunset-walk"
      },
      {
        id: "ci-1-3",
        itemType: CourseItemType.local_income_program,
        sortOrder: 3,
        time: "오후 6:30",
        title: "어촌 밥상 저녁식사",
        note: "천리포 마을회관에서 현지식 식사",
        slug: "village-dining"
      }
    ]
  },
  {
    id: "course-2",
    slug: "artistic-retreat",
    title: "예술가와 함께하는 힐링 여행",
    summary: "조용한 마을에서 공예 체험과 휴식을 즐기는 코스",
    images: ["/images/courses/course-02.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "커플/개인",
    durationType: "당일",
    linkedStayCount: 1,
    linkedExpCount: 1,
    linkedProgCount: 0,
    routeItems: [
      {
        id: "ci-2-1",
        itemType: CourseItemType.experience,
        sortOrder: 1,
        time: "오후 1:00",
        title: "씨글라스 업사이클링 공예",
        note: "나만의 기념품 만들기",
        slug: "beachcombing-workshop"
      },
      {
        id: "ci-2-2",
        itemType: CourseItemType.accommodation,
        sortOrder: 2,
        time: "오후 4:00",
        title: "천리포 어촌 민박 휴식",
        note: "조용한 민박집에서 휴식",
        slug: "cheonripo-minbak"
      }
    ]
  },
  {
    id: "course-3",
    slug: "family-2days-sowon",
    title: "가족형 1박 2일 느긋한 코스",
    summary: "숙소 주변에서 이동을 최소화하여 가족 모두가 편안한 1박 2일",
    description: "아이들과 함께하기 좋은 안전한 체류형 코스입니다.",
    images: ["/images/programs/prog-05.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "가족",
    durationType: "1박 2일",
    linkedStayCount: 0,
    linkedExpCount: 0,
    linkedProgCount: 3,
    routeItems: [
      {
        id: "ci-3-1",
        itemType: CourseItemType.local_income_program,
        sortOrder: 1,
        time: "Day 1 오후",
        title: "펜션 마당 키즈 풀장",
        note: "숙소 도착 후 안전한 물놀이",
        slug: "pension-kids-water-yard"
      },
      {
        id: "ci-3-2",
        itemType: CourseItemType.local_income_program,
        sortOrder: 2,
        time: "Day 1 저녁",
        title: "태안 로컬 식재료 팜다이닝",
        note: "건강한 저녁 식사",
        slug: "local-table-experience"
      },
      {
        id: "ci-3-3",
        itemType: CourseItemType.local_income_program,
        sortOrder: 3,
        time: "Day 2 오전",
        title: "활기찬 항구 아침 투어",
        note: "가족 아침 산책",
        slug: "harbor-morning-tour"
      }
    ]
  },
  {
    id: "course-4",
    slug: "sunset-couple-course",
    title: "만리포 노을 감성 커플 코스",
    summary: "해변 카페, 선셋워크, 분위기 있는 식사로 이어지는 데이트 동선",
    images: ["/images/courses/course-04.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "커플",
    durationType: "반나절",
    linkedStayCount: 1,
    linkedExpCount: 0,
    linkedProgCount: 1,
    routeItems: [
      {
        id: "ci-4-1",
        itemType: CourseItemType.experience,
        sortOrder: 1,
        title: "해변 카페 및 산책",
        note: "만리포 해변의 여유",
      },
      {
        id: "ci-4-2",
        itemType: CourseItemType.experience,
        sortOrder: 2,
        title: "선셋워크",
        note: "노을을 배경으로 인생사진",
      },
      {
        id: "ci-4-3",
        itemType: CourseItemType.accommodation,
        sortOrder: 3,
        title: "소원 낙조 펜션 체크인",
        note: "바다 뷰 숙소에서 휴식",
        slug: "sowon-house-01"
      },
      {
        id: "ci-4-4",
        itemType: CourseItemType.local_income_program,
        sortOrder: 4,
        title: "제철 어촌 밥상",
        note: "주민이 차려주는 맛있는 저녁",
        slug: "village-dining"
      }
    ]
  },
  {
    id: "course-5",
    slug: "fishing-village-half-day",
    title: "어촌 마을 반나절 산책",
    summary: "조용한 항구 마을에서 바다 내음을 느끼는 느린 여행",
    images: ["/images/programs/prog-08.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "개인/커플",
    durationType: "반나절",
    linkedStayCount: 0,
    linkedExpCount: 0,
    linkedProgCount: 2,
    routeItems: [
      {
        id: "ci-5-1",
        itemType: CourseItemType.local_income_program,
        sortOrder: 1,
        time: "오전 8:00",
        title: "항구 아침 투어",
        note: "해설사와 함께 모항항 걷기",
        slug: "harbor-morning-tour"
      },
      {
        id: "ci-5-2",
        itemType: CourseItemType.local_income_program,
        sortOrder: 2,
        time: "오전 10:00",
        title: "감태 포장 체험",
        note: "특산물 감태 이야기 듣기",
        slug: "gamtae-packing-class"
      },
      {
        id: "ci-5-3",
        itemType: CourseItemType.local_income_program,
        sortOrder: 3,
        time: "낮 12:00",
        title: "로컬 식사",
        note: "자유롭게 지역 맛집 방문",
      }
    ]
  },
  {
    id: "course-6",
    slug: "esg-beach-clean-course",
    title: "의미 있는 하루, ESG 해변 코스",
    summary: "해변 정화 활동과 업사이클링 공예를 결합한 가치 여행",
    images: ["/images/experiences/exp-04.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "단체/가족",
    durationType: "당일",
    linkedStayCount: 0,
    linkedExpCount: 1,
    linkedProgCount: 0,
    routeItems: [
      {
        id: "ci-6-1",
        itemType: CourseItemType.experience,
        sortOrder: 1,
        title: "해변 집결 및 플로깅",
        note: "만리포 해변 쓰레기 줍기",
      },
      {
        id: "ci-6-2",
        itemType: CourseItemType.experience,
        sortOrder: 2,
        title: "씨글라스 업사이클링",
        note: "주운 유리 조각으로 공예품 만들기",
        slug: "beachcombing-workshop"
      },
      {
        id: "ci-6-3",
        itemType: CourseItemType.local_income_program,
        sortOrder: 3,
        title: "로컬 간식 시간",
        note: "동네 빵집 방문",
      }
    ]
  },
  {
    id: "course-7",
    slug: "kids-local-experience-course",
    title: "우리아이 로컬 체험 당일치기",
    summary: "아이들이 자연 속에서 뛰놀고 배우는 생태형 코스",
    images: ["/images/programs/prog-04.jpg"],
    status: PublishStatus.published,
    regionId: "sowon",
    targetType: "아이동반",
    durationType: "당일",
    linkedStayCount: 0,
    linkedExpCount: 0,
    linkedProgCount: 1,
    routeItems: [
      {
        id: "ci-7-1",
        itemType: CourseItemType.local_income_program,
        sortOrder: 1,
        title: "소원 바다물길 놀이터",
        note: "자연이 만든 수영장에서 놀기",
        slug: "sowon-sea-water-playground"
      },
      {
        id: "ci-7-2",
        itemType: CourseItemType.local_income_program,
        sortOrder: 2,
        title: "마을 골목길 보물찾기",
        note: "마을 산책하며 사진 찍기",
      }
    ]
  }
];

